version: '3.0'
services:

  rasa-server:
    image: rasa-frontend:latest
    working_dir: /app
    build: "./"
    restart: always
    command: bash -c npm install && npm run serve
    ports:
    - '8000:8080'
    public: true
    networks:
    - all

networks:
  all:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
